# makefile for counters module
#
# altered from original version:
#  no longer builds test program
#
# Kyle Dotterrer, April 2016

CC = gcc
MAKE = make
CFLAGS = -Wall -pedantic -std=c11 -ggdb

OBJS = counters.o 
LIBS = 


counters.o: counters.h


clean:
	rm -f *~
	rm -f *.o
