# makefile for bag module
#
# altered from original version:
#  no longer builds test program
#
# Kyle Dotterrer, April 2016

CC = gcc
MAKE = make
CFLAGS = -Wall -pedantic -std=c11 -ggdb

OBJS = bag.o 
LIBS = 


bag.o: bag.h


clean:
	rm -f *~
	rm -f *.o
