# makefile for list module
#
# altered from original version:
#  no longer builds test program  
#
# Kyle Dotterrer, April 2016

CC = gcc
MAKE = make
CFLAGS = -Wall -pedantic -std=c11 -ggdb

OBJS = list.o
LIBS = 


list.o: list.h


clean:
	rm -f *~
	rm -f *.o
